import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendEmailVerification, GoogleAuthProvider, signInWithPopup, RecaptchaVerifier, PhoneAuthProvider, linkWithCredential, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyCCVWhITLbivYw1bfCu68R0vygBb7JndH0',authDomain:'aurexa-7e36c.firebaseapp.com',projectId:'aurexa-7e36c',storageBucket:'aurexa-7e36c.firebasestorage.app',messagingSenderId:'330095309934',appId:'1:330095309934:web:15d4f7891b16ef88a4227f'};
const API='https://aurexa-v3-staging.onrender.com';
const app=initializeApp(firebaseConfig); const auth=getAuth(app); let me=null; let catalog=[]; let page='home';
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function token(){return auth.currentUser?auth.currentUser.getIdToken():null}
async function api(path,opt={}){const t=await token(); const h=new Headers(opt.headers||{});h.set('Accept','application/json'); if(opt.body)h.set('Content-Type','application/json');if(t)h.set('Authorization','Bearer '+t);const r=await fetch(API+path,{...opt,headers:h});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||j.message||`HTTP ${r.status}`);return j}
function idk(){return crypto.randomUUID()}
function shell(){document.body.innerHTML=`<div class="app"><header><div><b>◆ AUREXA</b><small> BETA PÚBLICA · DIAMANTES VIRTUALES</small></div><button id="logout">Salir</button></header><div class="layout"><nav>${[['home','Inicio'],['packages','Paquetes'],['mining','Minería'],['payments','Pagos'],['history','Historial'],['creator','Creadora']].map(([k,v])=>`<button data-page="${k}">${v}</button>`).join('')}</nav><main id="view"></main></div></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});$('#logout').onclick=()=>signOut(auth)}
function card(title,body){return `<section class="card"><h2>${title}</h2>${body}</section>`}
async function load(){me=(await api('/api/v2/me')).data;catalog=(await api('/api/v2/catalog')).data.items||[]}
function home(){const p=me.profile,w=me.wallet;return `${card('Tu cuenta',`<p><b>${esc(auth.currentUser.email)}</b></p><p>Usuario: ${esc(p.username||'—')}</p><p>Plan: <b>${esc(p.mining_plan||'Sin plan')}</b></p><p>Hasta: ${esc(p.mining_until||'—')}</p>`)}${card('Billetera',`<div class="big">◆ ${Number(w.diamonds||0).toLocaleString()}</div><p>Diamantes virtuales disponibles</p><p>Estos diamantes solo tienen uso dentro de AUREXA y no representan dinero real.</p>`)}${me.profile.welcome_bonus_active?card('Bienvenida','Tu cuenta tiene el beneficio inicial activo.') : ''}`}
function packages(){return card('Paquetes disponibles',`<div class="grid">${catalog.map(p=>`<article class="card"><h3>${esc(p.name)}</h3><p><b>${p.cup} CUP</b> · ◆ ${p.diamonds}</p><p>${p.days} días · ${p.rate} nivel</p><button class="gold buy" data-code="${esc(p.code)}">Solicitar compra</button></article>`).join('')}</div><p class="muted">El pago se coordina manualmente por WhatsApp. La entrega de diamantes requiere aprobación de la creadora.</p>`)}
function mining(){return card('Minería',`<p>Plan actual: <b>${esc(me.profile.mining_plan||'Sin plan')}</b></p><p>La extracción se registra en el servidor y está protegida contra duplicados.</p><button class="gold" id="mine">Minar ahora</button><div id="mineResult"></div>`)}
function payments(){return card('Pagos',`<p>Selecciona un paquete y registra tu referencia de pago. No se acreditan diamantes desde el navegador.</p><div class="form"><select id="pkg">${catalog.map(p=>`<option value="${p.code}">${esc(p.name)} — ${p.cup} CUP / ◆ ${p.diamonds}</option>`).join('')}</select><input id="ref" placeholder="Referencia del pago (opcional)"><input id="name" placeholder="Nombre completo (opcional)"><input id="wa" placeholder="WhatsApp (opcional)"><button class="gold" id="request">Enviar solicitud</button><div id="payResult"></div></div>`)}
async function history(){const r=await api('/api/v2/purchases');const rows=r.data||[];return card('Historial de compras',rows.length?`<div class="rows">${rows.map(x=>`<div><b>${esc(x.package_code)}</b> · ${x.amount} CUP · ◆ ${x.tokens_requested}<br><small>${esc(x.status)} · ${new Date(x.created_at).toLocaleString()}</small>${x.delivery_error?`<p class="error">${esc(x.delivery_error)}</p>`:''}</div>`).join('')}</div>`:'Aún no tienes compras.')}
async function creator(){if((auth.currentUser.email||'').toLowerCase()!=='nunezyenis05@gmail.com')return card('Creadora','Acceso restringido.');const r=await api('/api/v2/creator/purchases');const rows=r.data||[];return card('Compras pendientes',rows.length?`<div class="rows">${rows.map(x=>`<div><b>${esc(x.package_code)}</b> · ${x.amount} CUP · ◆ ${x.tokens_requested}<br><small>${esc(x.status)} · ${esc(x.firebase_uid)}</small><button class="approve" data-id="${x.id}">Aprobar y entregar</button></div>`).join('')}</div>`:'No hay compras pendientes.');}
async function render(){const v=$('#view');if(!v)return;try{await load();let html=page==='home'?home():page==='packages'?packages():page==='mining'?mining():page==='payments'?payments():page==='history'?await history():await creator();v.innerHTML=html;bind();}catch(e){v.innerHTML=card('Error',`<p class="error">${esc(e.message)}</p><button class="gold" onclick="location.reload()">Reintentar</button>`)} }
function bind(){document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{page='payments';render().then(()=>{$('#pkg').value=b.dataset.code})});$('#mine')?.addEventListener('click',async()=>{try{const r=await api('/api/v2/mine',{method:'POST',headers:{'Idempotency-Key':idk()}});$('#mineResult').innerHTML=`<p class="ok">Minado registrado: ◆ ${esc(r.data?.diamonds_mined??r.data?.amount??'OK')}</p>`;await render()}catch(e){$('#mineResult').innerHTML=`<p class="error">${esc(e.message)}</p>`}});$('#request')?.addEventListener('click',async()=>{try{const r=await api('/api/v2/purchases',{method:'POST',headers:{'Idempotency-Key':idk()},body:JSON.stringify({package_code:$('#pkg').value,payment_reference:$('#ref').value,full_name:$('#name').value,whatsapp:$('#wa').value})});$('#payResult').innerHTML=`<p class="ok">Solicitud creada. ID: ${esc(r.data?.id||r.data?.purchase_id||'OK')}</p>`}catch(e){$('#payResult').innerHTML=`<p class="error">${esc(e.message)}</p>`}});document.querySelectorAll('.approve').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/v2/creator/purchases/'+encodeURIComponent(b.dataset.id)+'/approve',{method:'POST'});await render()}catch(e){alert(e.message);b.disabled=false}})}
function authScreen(){document.body.innerHTML=`<div class="auth"><div class="card"><h1>◆ AUREXA</h1><p>Beta pública · minería de diamantes virtuales</p><div class="tabs"><button id="loginTab">Entrar</button><button id="signupTab">Crear cuenta</button></div><form id="authForm"><input id="email" type="email" required placeholder="Correo electrónico"><input id="pass" type="password" required minlength="8" placeholder="Contraseña (mín. 8)"><input id="phone" type="tel" placeholder="Teléfono +535... solo al crear cuenta"><button class="gold" id="authBtn">Entrar</button><div id="authMsg"></div></form><button id="google">Continuar con Google</button></div></div>`;let signup=false;$('#signupTab').onclick=()=>{signup=true;$('#authBtn').textContent='Crear cuenta';$('#phone').style.display='block'};$('#loginTab').onclick=()=>{signup=false;$('#authBtn').textContent='Entrar';$('#phone').style.display='none'};$('#phone').style.display='none';$('#authForm').onsubmit=async e=>{e.preventDefault();const msg=$('#authMsg');try{if(signup){const c=await createUserWithEmailAndPassword(auth,$('#email').value,$('#pass').value);await sendEmailVerification(c.user);msg.innerHTML='<p class="ok">Cuenta creada. Verifica tu correo y vuelve a entrar. Para usar la beta también debes vincular tu teléfono mediante Firebase.</p>'}else await signInWithEmailAndPassword(auth,$('#email').value,$('#pass').value)}catch(x){msg.innerHTML=`<p class="error">${esc(x.message)}</p>`}};$('#google').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){$('#authMsg').innerHTML=`<p class="error">${esc(e.message)}</p>`}}}
onAuthStateChanged(auth,async u=>{if(!u){authScreen();return}if(!u.emailVerified){authScreen();$('#authMsg').innerHTML='<p class="error">Debes verificar tu correo antes de entrar.</p>';return}try{await load();shell();await render()}catch(e){authScreen();$('#authMsg').innerHTML=`<p class="error">${esc(e.message)}. Si acabas de crear la cuenta, verifica el correo y configura el teléfono.</p>`}});
