import{initializeApp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
const auth=getAuth(initializeApp({apiKey:atob('QUl6YVN5QmtWLUd0bTUyQXBITGpiS1o4VU0zV1NXcWNyaGZaVFVR'),authDomain:'aurexa-a7b3e.firebaseapp.com',projectId:'aurexa-a7b3e',storageBucket:'aurexa-a7b3e.firebasestorage.app',messagingSenderId:'709158763308',appId:'1:709158763308:web:382c2823908c0e07848a89'})),API='https://aurexa-v3-staging.onrender.com';let D={me:null,cat:[],vips:[],wells:[],page:'home',signup:false,creator:false};
const $=s=>document.querySelector(s),e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=x=>Number(x||0).toLocaleString('es-CU'),id=()=>crypto.randomUUID();
async function api(p,o={}){let h=new Headers(o.headers||{});h.set('Accept','application/json');if(o.body!==undefined)h.set('Content-Type','application/json');if(auth.currentUser)h.set('Authorization',`Bearer ${await auth.currentUser.getIdToken(true)}`);let r=await fetch(API+p,{...o,headers:h}),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error?.message||b?.error||`HTTP ${r.status}`);return b}
function toast(t){let x=document.querySelector('.toast')||Object.assign(document.body.appendChild(document.createElement('div')),{className:'toast'});x.textContent=t;clearTimeout(x.t);x.t=setTimeout(()=>x.remove(),3000)}
function authView(error=''){document.body.innerHTML=`<main class=auth><section class=auth-box><img src=/crypto-gaming-logo.svg class=auth-logo><h1>AUREXA</h1><p>CRYPTO GAMING · MINA · JUEGA · DISFRUTA</p><div class=tabs><button id=l class=${D.signup?'':'active'}>Entrar</button><button id=s class=${D.signup?'active':''}>Crear cuenta</button></div><form id=f><div class=field><label>Correo</label><input id=em type=email required autocomplete=email></div><div class=field><label>Contraseña</label><input id=pw type=password minlength=8 required autocomplete=${D.signup?'new-password':'current-password'}></div><button class="primary wide">${D.signup?'CREAR CUENTA':'ENTRAR'}</button><div id=m>${error?`<span class=bad>${e(error)}</span>`:''}</div><div class=auth-links><button type=button id=r>¿Olvidaste tu contraseña?</button><button type=button id=v>Reenviar verificación</button></div></form></section></main>`;$('l').onclick=()=>{D.signup=false;authView()};$('s').onclick=()=>{D.signup=true;authView()};$('f').onsubmit=async x=>{x.preventDefault();try{let r=D.signup?await createUserWithEmailAndPassword(auth,$('#em').value.trim(),$('#pw').value):await signInWithEmailAndPassword(auth,$('#em').value.trim(),$('#pw').value);if(D.signup){await sendEmailVerification(r.user);await signOut(auth);authView('Cuenta creada. Verifica tu correo antes de entrar.')}else{if(!r.user.emailVerified){await signOut(auth);authView('Debes verificar tu correo antes de entrar.')}else{await load();app()}}}catch(z){authView(z.message)}};$('r').onclick=async()=>{try{await sendPasswordResetEmail(auth,$('#em').value.trim());toast('Revisa tu correo.')}catch(z){toast(z.message)}};$('v').onclick=async()=>{if(!auth.currentUser)return toast('Inicia sesión primero.');try{await sendEmailVerification(auth.currentUser);toast('Correo enviado.')}catch(z){toast(z.message)}}}
async function load(){let [m,c]=await Promise.all([api('/api/v2/me'),api('/api/v2/catalog')]),d=c.data||{};D.me=m.data||{};D.cat=d.items||d.diamonds||d.packages||[];D.vips=d.vipMemberships||d.vips||d.memberships||[];D.wells=d.wells||d.miningPlans||[];try{await api('/api/v2/creator/purchases');D.creator=true}catch{D.creator=false}}
const nav=[['home','⌂','Inicio'],['mining','⛏','Minería'],['store','◇','Tienda'],['vip','♛','Membresías'],['wallet','◈','Wallet'],['history','◷','Historial'],['profile','♙','Perfil'],['support','♧','Soporte'],['settings','⚙','Configuración'],['notifications','♢','Notificaciones']];
function app(){document.body.innerHTML=`<div class=app><header class=topbar><button class="icon-btn mobile-menu" id=mm>☰</button><div class=brand><img src=/crypto-gaming-logo.svg><div><b>CRYPTO GAMING</b><small>AUREXA</small></div></div><div class=top-actions><button class=icon-btn data-p=notifications>♢</button><button class=profile-btn data-p=profile><i class=avatar>${e((D.me?.profile?.username||'A')[0].toUpperCase())}</i><span>${e(D.me?.profile?.username||'Jugador')}</span></button><button class=icon-btn id=out>Salir</button></div></header><div class=layout><aside class=sidebar id=sb><nav class=nav>${nav.map(x=>`<button data-p=${x[0]}><b>${x[1]}</b>${x[2]}</button>`).join('')}${D.creator?'<div class=nav-title>ADMINISTRACIÓN</div><button data-p=creator><b>♜</b>Creadora</button>':''}</nav></aside><main class=main id=view></main></div><div class=mobile-nav>${nav.slice(0,5).map(x=>`<button data-p=${x[0]}><b>${x[1]}</b>${x[2]}</button>`).join('')}</div></div>`;document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>go(b.dataset.p));$('out').onclick=()=>signOut(auth);$('mm').onclick=()=>sb.classList.toggle('open');go(D.page)}
const head=(a,b,c='')=>`<div class=page-head><div><div class=eyebrow>${e(a)}</div><h1>${b}</h1>${c?`<p>${c}</p>`:''}</div></div>`,empty=x=>`<div class=empty>${x}</div>`;
function cards(){if(!D.cat.length)return empty('El catálogo real no está disponible ahora. No se muestran precios inventados.');return`<div class="grid grid-4">${D.cat.map(x=>`<article class="card catalog-card"><span class=badge>DIAMANTES</span><div class=product-icon>◇</div><h3>${e(x.name||x.code)}</h3><p>${n(x.diamonds)} diamantes</p><div class=price>${n(x.cup??x.price_cup)} <small>CUP</small></div><button class="primary wide" data-buy=${e(x.code)}>COMPRAR</button></article>`).join('')}</div>`}
function vips(){if(!D.vips.length)return empty('No hay membresías activas.');return`<div class="grid grid-3">${D.vips.map(x=>`<article class="card vip-card"><span class="badge gold-badge">MEMBRESÍA</span><div class=product-icon>♛</div><h3>${e(x.name||x.code)}</h3><p>${n(x.total_diamonds)} diamantes · ${e(x.duration_days)} días</p><div class=price>${n(x.price_cup)} <small>CUP</small></div><p>${n(x.daily_diamonds)} diamantes/día</p><button class="primary wide" data-vip=${e(x.code)}>ACTIVAR</button></article>`).join('')}</div>`}
function diamondShop(){
  const fields=(x,i)=>{
    const code=x?.code||x?.package_code||x?.cup_code||'';
    const diamonds=x?.diamonds??x?.amount_diamonds??x?.quantity??null;
    const cup=x?.cup??x?.price_cup??x?.cost_cup??x?.price??null;
    const days=x?.duration_days??x?.days??null;
    return {code,diamonds,cup,days,name:x?.name||x?.label||code||`Paquete ${i+1}`};
  };
  const item=(i)=>fields(D.cat[i],i);
  return `<section class="diamond-shop-reference" aria-label="Tienda de paquetes de diamantes">
    ${[0,1,2,3,4,5].map(i=>{const x=item(i);return `<div class="diamond-live diamond-live-${i}" aria-live="polite"><strong>${e(x.name)}</strong><span>${x.cup==null?'Precio no disponible':n(x.cup)+' CUP'} · ${x.diamonds==null?'Diamantes no disponibles':n(x.diamonds)+' ◆'}${x.days==null?'':` · ${e(x.days)} días`}</span></div><button class="diamond-hotspot diamond-details-${i}" data-details="${e(x.code)}" aria-label="Ver detalles de ${e(x.name)}">Detalles</button><button class="diamond-hotspot diamond-buy-${i}" data-buy="${e(x.code)}" aria-label="Comprar ${e(x.name)}">Comprar</button>`}).join('')}
    <button class="diamond-hotspot diamond-back" data-p="home" aria-label="Regresar">Regresar</button>
  </section>`;
}
async function go(p){D.page=p;view.innerHTML='<div class=loading>Cargando…</div>';try{let h;if(p==='home')h=`<section class=reference-home aria-label="Dashboard AUREXA"><button class="reference-hotspot hs-mining" data-p=mining aria-label="Iniciar minería">Mini</button><button class="reference-hotspot hs-wallet" data-p=wallet aria-label="Ver wallet">Ver wallet</button><button class="reference-hotspot hs-history" data-p=history aria-label="Ver historial">Ver historial</button><button class="reference-hotspot hs-details" data-p=mining aria-label="Ver detalles">Ver detalles</button><button class="reference-hotspot hs-back" data-p=home aria-label="Regresar">Regresar</button></section>`;if(p==='store')h=diamondShop();if(p==='vip')h=head('MEMBRESÍAS','Membresías AUREXA','Precios, duración y recompensas reales.')+vips();if(p==='mining')h=await mining();if(p==='wallet')h=wallet();if(p==='history')h=await history();if(p==='profile')h=profile();if(p==='support')h=support();if(p==='settings')h=settings();if(p==='notifications')h=await notifications();if(p==='creator')h=await creator();view.innerHTML=h;actions()}catch(x){view.innerHTML=`<div class=error>No se pudo cargar esta pantalla.<br>${e(x.message)}</div>`}}
async function mining(){return `<section class="mining-reference" aria-label="Minería AUREXA"><button class="mining-hotspot mine-mini" data-mine="mini" aria-label="Iniciar minería Mini">Mini</button><button class="mining-hotspot mine-small" data-mine="small" aria-label="Iniciar minería Pequeño">Pequeño</button><button class="mining-hotspot mine-medium" data-mine="medium" aria-label="Iniciar minería Medio">Medio</button><button class="mining-hotspot mine-start" data-mine="mini" aria-label="Iniciar minería">Iniciar minería</button><button class="mining-hotspot mine-wallet" data-p="wallet" aria-label="Ver wallet">Ver wallet</button><button class="mining-hotspot mine-history" data-p="history" aria-label="Ver historial">Ver historial</button><button class="mining-hotspot mine-details" data-p="mining" aria-label="Ver detalles">Ver detalles</button><button class="mining-hotspot mine-back" data-p="home" aria-label="Regresar">Regresar</button></section>`}
function wallet(){return head('WALLET','Mis diamantes','Saldo y retiros.')+`<div class="grid grid-3"><div class=stat-card><span>SALDO</span><strong>◇ ${n(D.me?.wallet?.diamonds)}</strong></div><div class=stat-card><span>REFERENCIA</span><strong>${n(Number(D.me?.wallet?.diamonds||0)*5)} CUP</strong></div><div class=stat-card><span>MÍNIMO RETIRO</span><strong>10 ◆</strong></div></div><div class=section-title><h2>Solicitar retiro</h2></div><section class=card><div class=form-grid><div class=field><label>Diamantes</label><input id=wa type=number min=10 value=10></div><div class=field><label>Método</label><select id=wm><option value=whatsapp>WhatsApp</option><option value=transfer>Transferencia</option></select></div><div class="field full"><label>Destino</label><input id=wd placeholder="Destino autorizado"></div></div><button class=primary id=withdraw>Solicitar retiro</button></section>`}
async function history(){let t=[],p=[];try{[t,p]=await Promise.all([api('/api/v2/me/wallet/transactions').then(x=>x.data||[]),api('/api/v2/purchases').then(x=>x.data||[])])}catch{}return head('HISTORIAL','Actividad','Movimientos y compras.')+(t.length?`<section class=card><table class=table><tr><th>TIPO</th><th>MONTO</th><th>FECHA</th></tr>${t.slice(0,25).map(x=>`<tr><td>${e(x.entry_type||x.type)}</td><td>${e(x.amount??'')} ◆</td><td>${e(x.created_at||'')}</td></tr>`).join('')}</table></section>`:empty('No hay movimientos.'))+`<div class=section-title><h2>Compras</h2></div>`+(p.length?`<section class=card><table class=table><tr><th>ESTADO</th><th>PAQUETE</th><th>FECHA</th></tr>${p.slice(0,20).map(x=>`<tr><td>${e(x.status)}</td><td>${e(x.package_code||x.cup_code)}</td><td>${e(x.created_at||'')}</td></tr>`).join('')}</table></section>`:empty('No hay compras.'))}
function profile(){let p=D.me?.profile||{};return head('PERFIL','Mi cuenta','Identidad y estado.')+`<div class="grid grid-2"><section class=card><div class=avatar style="width:64px;height:64px">${e((p.username||'A')[0].toUpperCase())}</div><h2>${e(p.username||'Jugador')}</h2><p>${e(p.email||auth.currentUser?.email||'')}</p></section><section class=card><div class=row><span>Diamantes</span><b>${n(D.me?.wallet?.diamonds)} ◆</b></div><div class=row><span>Plan</span><b>${e(p.mining_plan||'none')}</b></div><div class=row><span>Correo</span><b>${auth.currentUser?.emailVerified?'Verificado':'Pendiente'}</b></div></section></div>`}
function support(){return head('SOPORTE','Ayuda','Escribe tu consulta y la enviamos al canal oficial.')+`<section class=card><div class=field><label>Mensaje</label><textarea id=sm placeholder="Describe tu problema..."></textarea></div><button class=primary id=sendSupport>ENVIAR</button></section>`}
function settings(){return head('CONFIGURACIÓN','Ajustes','Seguridad y preferencias.')+`<section class=card><div class=settings-item><b>Correo verificado</b><span class=badge>${auth.currentUser?.emailVerified?'SÍ':'PENDIENTE'}</span></div><div class=settings-item><b>Economía</b><span class=badge>VIRTUAL</span></div><div class=settings-item><b>Notificaciones</b><button class="switch on"><i></i></button></div></section>`}
async function notifications(){let t=[];try{t=(await api('/api/v2/me/wallet/transactions')).data||[]}catch{}return head('AVISOS','Notificaciones','Actividad reciente.')+(t.length?t.slice(0,10).map(x=>`<div class="card row"><span>◇ ${e(x.entry_type||x.type)}<small>${e(x.created_at||'')}</small></span><b>${e(x.amount??'')} ◆</b></div>`).join(''):empty('No hay notificaciones.'))}
async function creator(){if(!D.creator)return head('CREADORA','Acceso restringido','Esta sección solo aparece para cuentas autorizadas.');let p=[];try{p=(await api('/api/v2/creator/purchases')).data||[]}catch{}return head('CREADORA','Centro de control','Compras y operaciones administrativas.')+`<section class=card><h3>Compras</h3>${p.slice(0,15).map(x=>`<div class=row><span>${e(x.package_code||x.cup_code)}</span><span class=badge>${e(x.status)}</span></div>`).join('')||empty('No hay compras.')}</section>`}
function actions(){document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>go(b.dataset.p));$('#referenceSignout')?.addEventListener('click',()=>signOut(auth));$('#referenceMenu')?.addEventListener('click',()=>document.querySelector('.sidebar')?.classList.toggle('open'));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=async()=>{if(!b.dataset.buy)return toast('Este paquete no está disponible ahora.');try{await api('/api/v2/purchases',{method:'POST',headers:{'Idempotency-Key':id()},body:JSON.stringify({package_code:b.dataset.buy})});toast('Solicitud enviada para aprobación.')}catch(x){toast(x.message)}});document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>{if(!b.dataset.details)return toast('Detalles no disponibles ahora.');const x=D.cat.find(v=>(v.code||v.package_code||v.cup_code)===b.dataset.details);toast(x?`${x.name||x.code}: ${n(x.cup??x.price_cup??x.price)} CUP · ${n(x.diamonds)} diamantes`:'Detalles no disponibles ahora.')});document.querySelectorAll('[data-vip]').forEach(b=>b.onclick=()=>toast('La activación se procesa por compra aprobada.'));document.querySelectorAll('[data-mine]').forEach(b=>b.onclick=async()=>{try{await api('/api/v2/mine',{method:'POST',headers:{'Idempotency-Key':id()},body:JSON.stringify({plan_code:b.dataset.mine})});toast('Minería iniciada.');await load();go('mining')}catch(x){toast(x.message)}});document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=async()=>{try{await api('/api/v2/mining/'+encodeURIComponent(b.dataset.claim)+'/claim',{method:'POST',headers:{'Idempotency-Key':id()}});toast('Recompensa reclamada.');await load();go('mining')}catch(x){toast(x.message)}});$('#withdraw')?.addEventListener('click',async()=>{try{await api('/api/v2/withdrawals',{method:'POST',headers:{'Idempotency-Key':id()},body:JSON.stringify({amount:Number($('#wa').value),payout_method:$('#wm').value,payout_destination:$('#wd').value.trim()})});toast('Retiro solicitado.')}catch(x){toast(x.message)}});$('#sendSupport')?.addEventListener('click',async()=>{try{await api('/api/v2/contact',{method:'POST',body:JSON.stringify({message:$('#sm').value.trim()})});toast('Consulta enviada.')}catch(x){toast(x.message)}})}
onAuthStateChanged(auth,async u=>{if(!u){authView();return}try{if(!u.emailVerified){await signOut(auth);authView('Debes verificar tu correo antes de entrar.');return}await load();app()}catch(x){authView(x.message)}});