(function(){
  const styles=['/aurexa-mobile-visual.css?v=20260907-1','/aurexa-cinematic-fix.css?v=20260907-2','/aurexa-scene-pass.css?v=20260906-2','/aurexa-gothic-realm-v2.css?v=20260907-1'];
  styles.forEach(href=>{if(!document.querySelector('link[href^="'+href.split('?')[0]+'"]')){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}});
  const navLabels=[['home','Inicio','⌂'],['mining','Mina','⚒'],['packages','Tienda','▣'],['wallet','Mis Diamantes','◇'],['history','Historial','◷'],['profile','Perfil','♙'],['support','Soporte','◉'],['settings','Configuración','⚙']];
  const nav=()=>document.querySelector('#side');
  let wells=[];
  const apiBase='https://aurexa-v3-staging.onrender.com';
  async function loadWells(){try{const r=await fetch(apiBase+'/api/v2/catalog',{headers:{Accept:'application/json'}});const j=await r.json();wells=j?.data?.wells||[];return wells}catch{return []}}
  function ensureNav(){const n=nav();if(!n||n.dataset.referenceBuilt)return;n.dataset.referenceBuilt='1';const buttons=[...n.querySelectorAll('button[data-page]')];const by=new Map(buttons.map(b=>[b.dataset.page,b]));const quote=n.querySelector('.side-quote');navLabels.forEach(([key,label,icon])=>{if(by.has(key))return;const b=document.createElement('button');b.dataset.page=key;b.innerHTML='<b>'+icon+'</b><span>'+label+'</span>';if(quote)n.insertBefore(b,quote);else n.appendChild(b)})}
  function enhanceHome(){const view=document.querySelector('#view');if(!view||view.dataset.referenceEnhanced||!view.querySelector('.hero-card'))return;view.dataset.referenceEnhanced='1';const grid=view.querySelector('.dashboard-grid');if(!grid)return;grid.classList.add('reference-dashboard');const main=grid.firstElementChild,profile=grid.querySelector('.profile-panel');if(main)main.classList.add('reference-main');if(profile)profile.classList.add('reference-profile');const q=main&&main.querySelector('.quick-grid');if(q)[...q.querySelectorAll('.quick-card')].forEach((c,i)=>c.dataset.referenceArt=['mine','store','profile','history'][i]||'');if(main){const activity=document.createElement('section');activity.className='reference-activity card';activity.innerHTML='<div class="card-title"><h3>Actividad Reciente</h3><span>Ver todo</span></div><div class="activity-list"><div><b>◇</b><span>Actividad registrada en el reino<small>Hace unos minutos</small></span></div><div><b>◉</b><span>Movimiento de cuenta<small>Reciente</small></span></div><div><b>♛</b><span>Progreso del jugador<small>Actualizado</small></span></div></div>';grid.appendChild(activity)}}
  function enhanceMining(){const btn=document.querySelector('#mineBtn');if(!btn||btn.dataset.wellEnhanced)return;btn.dataset.wellEnhanced='1';const wrap=document.createElement('div');wrap.className='aurexa-well-selector';wrap.style.cssText='margin:14px 0';wrap.innerHTML='<label style="display:block;color:#d9bd82;font:700 11px Cinzel,serif;letter-spacing:1px;margin-bottom:6px">POZO DE MINERÍA</label><select id="aurexaWell" style="width:100%;padding:12px;background:#0b080d;color:#f4ead5;border:1px solid #c99b45;border-radius:3px"></select><small id="aurexaWellInfo" style="display:block;margin-top:7px;color:#9c8f86"></small>';btn.parentNode.insertBefore(wrap,btn);const sel=wrap.querySelector('#aurexaWell'),info=wrap.querySelector('#aurexaWellInfo');const fill=()=>{sel.innerHTML=wells.map(w=>`<option value="${String(w.code).replace(/"/g,'&quot;')}">${String(w.name||w.code)} · ${Number(w.input_diamonds||0).toLocaleString()} ◆ · ${Number(w.duration_days||0)} días</option>`).join('');const w=wells.find(x=>x.code===sel.value)||wells[0];info.textContent=w?`Costo ${Number(w.input_diamonds||0).toLocaleString()} ◆ · recompensa ${Number(w.reward_diamonds||0).toLocaleString()} ◆`:''};fill();sel.onchange=fill;btn.disabled=false}
  function enhancePackages(){const products=document.querySelector('.products');if(!products||products.dataset.wellsEnhanced)return;if(products.querySelector('[data-buy]'))return;products.dataset.wellsEnhanced='1';if(!wells.length)return;products.innerHTML=wells.map(w=>`<article class="product"><span class="product-icon">◇</span><h3>${String(w.name||w.code)}</h3><strong>◆ ${Number(w.input_diamonds||0).toLocaleString()}</strong><p>Entrada al pozo · ${Number(w.duration_days||0)} días · recompensa ${Number(w.reward_diamonds||0).toLocaleString()} ◆</p><div class="price">${Number(w.price_cup||0).toLocaleString()} <small>CUP</small></div><button class="primary wide" data-buy="${String(w.code).replace(/"/g,'&quot;')}">COMPRAR</button></article>`).join('')}
  const originalFetch=window.fetch.bind(window);window.fetch=async function(input,init={}){const url=typeof input==='string'?input:input?.url||'';if(url.includes('/api/v2/mine')&&init.body){try{const body=JSON.parse(init.body);const sel=document.querySelector('#aurexaWell');if(!body.plan_code&&!body.planCode&&sel){body.plan_code=sel.value;init={...init,body:JSON.stringify(body)}}}catch{}}return originalFetch(input,init)};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(b){const w=wells.find(x=>x.code===b.dataset.buy);if(w){e.preventDefault();location.href='https://wa.me/5355720394?text='+encodeURIComponent(`Hola, quiero solicitar el pozo ${w.name} de AUREXA por ${w.price_cup} CUP (${w.input_diamonds} diamantes).`)}}});
  new MutationObserver(()=>{ensureNav();enhanceHome();if(document.querySelector('#mineBtn')){if(!wells.length)loadWells().then(enhanceMining);else enhanceMining()}if(document.querySelector('.products')){if(!wells.length)loadWells().then(enhancePackages);else enhancePackages()}}).observe(document.documentElement,{subtree:true,childList:true});
  ensureNav();enhanceHome();loadWells().then(()=>{enhanceMining();enhancePackages()});
})();
