(function(){
  const style='/aurexa-mobile-visual.css?v=20260907-1';
  if(!document.querySelector('link[href^="/aurexa-mobile-visual.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href=style;document.head.appendChild(l)}
  const navLabels=[['home','Inicio','⌂'],['mining','Mina','⚒'],['packages','Tienda','▣'],['chat','Chat / Trading','▰'],['wallet','Mis Diamantes','◇'],['history','Historial','◷'],['ranking','Ranking','♛'],['support','Soporte','◉'],['settings','Configuración','⚙']];
  const nav=()=>document.querySelector('#side');
  function ensureNav(){const n=nav();if(!n||n.dataset.referenceBuilt)return;n.dataset.referenceBuilt='1';const buttons=[...n.querySelectorAll('button[data-page]')];const by=new Map(buttons.map(b=>[b.dataset.page,b]));const quote=n.querySelector('.side-quote');navLabels.forEach(([key,label,icon])=>{if(by.has(key))return;const b=document.createElement('button');b.dataset.page=key;b.innerHTML='<b>'+icon+'</b><span>'+label+'</span>';if(quote)n.insertBefore(b,quote);else n.appendChild(b)});n.addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(!b)return;const target=b.dataset.page;if(target==='chat'||target==='ranking'){e.preventDefault();const support=n.querySelector('button[data-page="support"]');if(support)support.click()}})}
  function enhanceHome(){const view=document.querySelector('#view');if(!view||view.dataset.referenceEnhanced||!view.querySelector('.hero-card'))return;view.dataset.referenceEnhanced='1';const grid=view.querySelector('.dashboard-grid');if(!grid)return;grid.classList.add('reference-dashboard');const main=grid.firstElementChild,profile=grid.querySelector('.profile-panel');if(main)main.classList.add('reference-main');if(profile)profile.classList.add('reference-profile');const q=main&&main.querySelector('.quick-grid');if(q)[...q.querySelectorAll('.quick-card')].forEach((c,i)=>c.dataset.referenceArt=['mine','store','chat','rank'][i]||'');if(main){const activity=document.createElement('section');activity.className='reference-activity card';activity.innerHTML='<div class="card-title"><h3>Actividad Reciente</h3><span>Ver todo</span></div><div class="activity-list"><div><b>◇</b><span>Actividad registrada en el reino<small>Hace unos minutos</small></span></div><div><b>◉</b><span>Movimiento de cuenta<small>Reciente</small></span></div><div><b>▰</b><span>Comunidad y chat<small>Disponible próximamente</small></span></div><div><b>♛</b><span>Progreso del jugador<small>Actualizado</small></span></div></div>';grid.appendChild(activity)}}
  new MutationObserver(()=>{ensureNav();enhanceHome()}).observe(document.documentElement,{subtree:true,childList:true});ensureNav();enhanceHome();
})();
